# GlobeCo Order Service Configuration

# External Service URLs
security:
  service:
    url: http://globeco-security-service:8000

portfolio:
  service:
    url: http://globeco-portfolio-service:8000

# Cache Configuration
cache:
  security:
    ttl: 300  # 5 minutes in seconds
    size: 1000  # Maximum number of entries
  portfolio:
    ttl: 300  # 5 minutes in seconds
    size: 1000  # Maximum number of entries

# Service Timeout Configuration (for future use)
service:
  timeout:
    connect: 5000  # 5 seconds in milliseconds
    read: 30000    # 30 seconds in milliseconds

# Metrics Configuration
metrics:
  custom:
    enabled: true
    http:
      enabled: true
      request:
        enabled: true
        route-sanitization-enabled: true
        max-path-segments: 10
        metric-caching-enabled: true
        max-cache-size: 1000
        detailed-logging-enabled: false
  debug:
    enabled: true  # Enable debug metrics endpoint for validation

# Bulk Submission Configuration
bulk:
  submission:
    enabled: true
    trade-service:
      timeout-ms: 60000
      max-batch-size: 100
      connection-timeout-ms: 10000
      read-timeout-ms: 60000
      max-retries: 2
      retry-delay-ms: 1000
      exponential-backoff: true
    fallback:
      enabled: false
      max-individual-orders: 10
      individual-timeout-ms: 30000
      auto-fallback-on-errors: true
      fallback-trigger-status-codes: [503, 429, 502, 504]
    monitoring:
      performance-monitoring-enabled: true
      success-rate-monitoring-enabled: true
      success-rate-threshold: 0.95
      success-rate-window-minutes: 15
      latency-monitoring-enabled: true
      max-acceptable-latency-ms: 30000
      error-rate-monitoring-enabled: true
      max-error-rate: 0.05
      detailed-logging-enabled: true
      log-performance-metrics: true
    performance:
      db-pool-optimization-enabled: true
      max-db-connections: 5
      batch-db-updates-enabled: true
      db-update-batch-size: 50
      async-processing-enabled: true
      async-thread-pool-size: 3
      memory-optimization-enabled: true
      max-memory-usage-mb: 256

# Logging Configuration
logging:
  level:
    root: ${LOG_LEVEL:INFO}  # Can be overridden by LOG_LEVEL environment variable, defaults to INFO
    org.kasbench.globeco_order_service: ${LOG_LEVEL:DEBUG}  # Service-specific logging controlled by LOG_LEVEL
    org.kasbench.globeco_order_service.service: ${LOG_LEVEL:DEBUG}  # All service classes at DEBUG level
    org.kasbench.globeco_order_service.controller: ${LOG_LEVEL:DEBUG}  # All controller classes at DEBUG level
    org.kasbench.globeco_order_service.service.SecurityServiceClient: ${LOG_LEVEL:DEBUG}
    org.kasbench.globeco_order_service.service.PortfolioServiceClient: ${LOG_LEVEL:DEBUG}
    org.kasbench.globeco_order_service.service.SecurityCacheService: ${LOG_LEVEL:DEBUG}
    org.kasbench.globeco_order_service.service.PortfolioCacheService: ${LOG_LEVEL:DEBUG} 