# GlobeCo Order Service Configuration

# External Service URLs
security:
  service:
    url: http://globeco-security-service:8000

portfolio:
  service:
    url: http://globeco-portfolio-service:8000

# Cache Configuration
cache:
  security:
    ttl: 300  # 5 minutes in seconds
    size: 1000  # Maximum number of entries
  portfolio:
    ttl: 300  # 5 minutes in seconds
    size: 1000  # Maximum number of entries

# Service Timeout Configuration (for future use)
service:
  timeout:
    connect: 5000  # 5 seconds in milliseconds
    read: 30000    # 30 seconds in milliseconds

# Metrics Configuration
metrics:
  custom:
    enabled: true
    http:
      enabled: true
      request:
        enabled: true
        route-sanitization-enabled: true
        max-path-segments: 10
        metric-caching-enabled: true
        max-cache-size: 1000
        detailed-logging-enabled: false
  debug:
    enabled: true  # Enable debug metrics endpoint for validation

# Logging Configuration
logging:
  level:
    root: ${LOG_LEVEL:INFO}  # Can be overridden by LOG_LEVEL environment variable, defaults to INFO
    org.kasbench.globeco_order_service: ${LOG_LEVEL:DEBUG}  # Service-specific logging controlled by LOG_LEVEL
    org.kasbench.globeco_order_service.service: ${LOG_LEVEL:DEBUG}  # All service classes at DEBUG level
    org.kasbench.globeco_order_service.controller: ${LOG_LEVEL:DEBUG}  # All controller classes at DEBUG level
    org.kasbench.globeco_order_service.service.SecurityServiceClient: ${LOG_LEVEL:DEBUG}
    org.kasbench.globeco_order_service.service.PortfolioServiceClient: ${LOG_LEVEL:DEBUG}
    org.kasbench.globeco_order_service.service.SecurityCacheService: ${LOG_LEVEL:DEBUG}
    org.kasbench.globeco_order_service.service.PortfolioCacheService: ${LOG_LEVEL:DEBUG} 