apiVersion: v1
kind: Service
metadata:
  name: globeco-order-service
  namespace: globeco
  labels:
    app: globeco-order-service
spec:
  selector:
    app: globeco-order-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP 